#pragma once

/* Generated by stormc/err_codegen.py. */

enum stc_err_code {
	STC_ERR_OK,
	STC_ERR_GLOBAL_ALLOCATOR_UNINITED,
	STC_ERR_OS_RESERVE_FAILED,
	STC_ERR_OS_COMMIT_FAILED,
	STC_ERR_OS_FREE_FAILED,
	STC_ERR_OS_UNMAP_FAILED,
	STC_ERR_STACK_BASE_OFFSET_GREATER_THAN_SIZE,
	STC_ERR_FILE_COPY_TO_STRING8_FAILED,
	STC_ERR_FILE_OPEN_FAILED,
	STC_ERR_FILE_READ_FAILED,
	STC_ERR_FILE_WRITE_FAILED,
	STC_ERR_FILE_CLOSE_FAILED,
	STC_ERR_FILE_STAT_FAILED,
	STC_ERR_INVALID_ARGUMENT,
	STC_ERR_OUT_OF_MEMORY,
	STC_ERR_UNSUPPORTED,
	STC_ERR_COUNT,
};

static const char *stc_err_table_literal[STC_ERR_COUNT] = {
	[STC_ERR_OK] = "ok",
	[STC_ERR_GLOBAL_ALLOCATOR_UNINITED] = "global allocator uninited",
	[STC_ERR_OS_RESERVE_FAILED] = "os reserve failed",
	[STC_ERR_OS_COMMIT_FAILED] = "os commit failed",
	[STC_ERR_OS_FREE_FAILED] = "os free failed",
	[STC_ERR_OS_UNMAP_FAILED] = "os unmap failed",
	[STC_ERR_STACK_BASE_OFFSET_GREATER_THAN_SIZE] = "stack base offset greater than size",
	[STC_ERR_FILE_COPY_TO_STRING8_FAILED] = "file copy to string8 failed",
	[STC_ERR_FILE_OPEN_FAILED] = "file open failed",
	[STC_ERR_FILE_READ_FAILED] = "file read failed",
	[STC_ERR_FILE_WRITE_FAILED] = "file write failed",
	[STC_ERR_FILE_CLOSE_FAILED] = "file close failed",
	[STC_ERR_FILE_STAT_FAILED] = "file stat failed",
	[STC_ERR_INVALID_ARGUMENT] = "invalid argument",
	[STC_ERR_OUT_OF_MEMORY] = "out of memory",
	[STC_ERR_UNSUPPORTED] = "unsupported",
};
