#pragma once

/* Generated by stormc/err_codegen.py. */

enum stc_err_code {
	STC_ERR_OK,
	STC_ERR_GLOBAL_ALLOCATOR_UNINITED,
	STC_ERR_OS_RESERVE_FAILED,
	STC_ERR_OS_COMMIT_FAILED,
	STC_ERR_OS_FREE_FAILED,
	STC_ERR_OS_UNMAP_FAILED,
	STC_ERR_STACK_BASE_OFFSET_GREATER_THAN_SIZE,
	STC_ERR_FILE_COPY_TO_STRING8_FAILED,
	STC_ERR_FILE_OPEN_FAILED,
	STC_ERR_FILE_READ_FAILED,
	STC_ERR_FILE_WRITE_FAILED,
	STC_ERR_FILE_CLOSE_FAILED,
	STC_ERR_FILE_STAT_FAILED,
	STC_ERR_INVALID_ARGUMENT,
	STC_ERR_OUT_OF_MEMORY,
	STC_ERR_UNSUPPORTED,
	STC_ERR_COUNT,
};

static const char *stc_err_table_literal[STC_ERR_COUNT] = {
	"ok",
	"global allocator uninited",
	"os reserve failed",
	"os commit failed",
	"os free failed",
	"os unmap failed",
	"stack base offset greater than size",
	"file copy to string8 failed",
	"file open failed",
	"file read failed",
	"file write failed",
	"file close failed",
	"file stat failed",
	"invalid argument",
	"out of memory",
	"unsupported",
};
